### ISSUE TITLE
No such file or directory: 'params.npz'

### ISSUE THREAD

**Issue by Bravo2333** [florian6973/btt-spyx#1]
Is params.npz a dataset? Anyone can tell me where can i get it please?

**Comment by florian6973** [comment]
`params.npz` is a weight file that I created to compare the two implementations (the official one with tf and mine with spyx), so that I can have the same weights for each neural network.

I just pushed the file if you would like to test, but I strongly suggest fixing the code to use random initialization (it should be just uncommenting/commenting lines).

**Comment by Bravo2333** [comment]
> `params.npz` is a weight file that I created to compare the two implementations (the official one with tf and mine with spyx), so that I can have the same weights for each neural network.
> 
> I just pushed the file if you would like to test, but I strongly suggest fixing the code to use random initialization (it should be just uncommenting/commenting lines).

Yes, I saw that initialization process, and the code has run successfully. I can finally learn step by step. Thank you.
